#!/usr/bin/env python3
"""PreToolUse advisory guard: denies the handful of Bash commands that are never right, fast, and nothing else."""

from __future__ import annotations

import fnmatch
import json
import os
import re
import shlex
import subprocess
import sys

PROTECTED = ("main", "master", "trunk", "prod", "production", "release/*", "hotfix/*")
TRAILER = re.compile(r"co-authored-by\s*:|generated with|generated by|\U0001F916", re.I)
SEGMENT_SPLIT = re.compile(r"\s*(?:&&|\|\||[;|\n])\s*")
DESTRUCTIVE = {
    "rebase": "rebases rewrite history",
    "reset": "reset discards work",
    "checkout": "checkout discards uncommitted work; move with switch",
    "restore": "restore discards uncommitted work",
    "clean": "clean deletes untracked files",
    "filter-branch": "filter-branch rewrites history",
    "filter-repo": "filter-repo rewrites history",
    "update-ref": "update-ref bypasses the branch model",
}


def protected_patterns() -> tuple:
    """Patterns from the repo's komodo.json when present, else the built-in set."""
    try:
        root = subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, timeout=3).stdout.strip()
        path = os.path.join(root, "komodo.json")
        if root and os.path.isfile(path):
            data = json.load(open(path, encoding="utf-8"))
            if isinstance(data.get("protected"), list):
                return tuple(str(item) for item in data["protected"])
    except Exception:
        pass
    return PROTECTED


def is_protected(name: str, patterns: tuple) -> bool:
    """Whether a ref name matches a protected pattern."""
    name = name.strip().strip("'\"")
    for prefix in ("refs/heads/", "origin/"):
        if name.startswith(prefix):
            name = name[len(prefix):]
    return any(fnmatch.fnmatchcase(name, pattern) for pattern in patterns)


def current_branch(cwd: str) -> str:
    """The checked-out branch in cwd, or empty."""
    try:
        return subprocess.run(["git", "symbolic-ref", "--short", "-q", "HEAD"], cwd=cwd, capture_output=True, text=True, timeout=3).stdout.strip()
    except Exception:
        return ""


def git_findings(tokens: list, cwd: str, patterns: tuple) -> list:
    """Reasons to deny one git invocation."""
    args = tokens[1:]
    index = 0
    while index < len(args) and args[index].startswith("-"):
        if args[index] in ("-C", "-c", "--git-dir", "--work-tree"):
            if args[index] == "-C" and index + 1 < len(args):
                cwd = args[index + 1]
            index += 2
        else:
            index += 1
    if index >= len(args):
        return []
    sub, rest = args[index], args[index + 1:]
    if sub in DESTRUCTIVE:
        return ["git %s: %s" % (sub, DESTRUCTIVE[sub])]
    if sub == "push":
        out = []
        if any(arg in ("-f", "--force", "--force-with-lease", "--force-if-includes", "--mirror", "--delete", "-d") or arg.startswith(("--force", "+")) for arg in rest):
            out.append("git push: force or delete is never part of the flow")
        positional = [arg for arg in rest if not arg.startswith("-")]
        for spec in positional[1:]:
            destination = spec.split(":", 1)[1] if ":" in spec else spec
            if destination == "HEAD":
                destination = current_branch(cwd)
            if is_protected(destination, patterns):
                out.append("git push to %s: open a pull request instead" % destination)
        if len(positional) < 2:
            branch = current_branch(cwd)
            if branch and is_protected(branch, patterns):
                out.append("git push from %s: open a pull request instead" % branch)
        return out
    if sub == "commit":
        out = []
        if "--amend" in rest or "--no-verify" in rest or "-n" in rest:
            out.append("git commit: --amend and --no-verify are refused")
        branch = current_branch(cwd)
        if branch and is_protected(branch, patterns):
            out.append("git commit on %s: create a branch first" % branch)
        return out
    if sub == "merge":
        branch = current_branch(cwd)
        if branch and is_protected(branch, patterns):
            return ["git merge on %s: landing is the human's merge button" % branch]
        return []
    if sub == "switch" and any(arg in ("-f", "--force", "--discard-changes") for arg in rest):
        return ["git switch: --discard-changes throws away uncommitted work"]
    if sub == "branch" and any(arg in ("-D", "-f", "--force") for arg in rest):
        return ["git branch: forced delete or move is refused"]
    return []


def analyze(command: str, cwd: str) -> list:
    """Every reason to deny a Bash command."""
    findings = []
    patterns = protected_patterns()
    if re.search(r"\bgit\b[^\n;|&]*\b(?:commit|merge)\b", command) and TRAILER.search(command):
        findings.append("commit message carries a co-author or generated-by trailer")
    for segment in SEGMENT_SPLIT.split(command):
        try:
            tokens = shlex.split(segment)
        except ValueError:
            tokens = segment.split()
        tokens = [token for token in tokens if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*=", token)] if tokens else []
        if not tokens:
            continue
        name = os.path.basename(tokens[0])
        if name == "sudo":
            findings.append("sudo is refused; run it yourself")
        elif name == "rm":
            flags = "".join(token[1:] for token in tokens[1:] if token.startswith("-") and not token.startswith("--"))
            if ("r" in flags and "f" in flags) or ("--recursive" in tokens and "--force" in tokens):
                findings.append("rm -rf is refused; delete deliberately by hand")
        elif name == "git":
            findings.extend(git_findings(tokens, cwd, patterns))
        elif name == "gh" and len(tokens) > 2 and tokens[1] == "pr" and tokens[2] == "merge":
            findings.append("gh pr merge: landing is the human's merge button")
    return findings


def main() -> None:
    """Reads the tool payload, denies on findings, and stays silent otherwise; any internal error fails open."""
    try:
        payload = json.loads(sys.stdin.read() or "{}")
        if payload.get("tool_name") != "Bash":
            return
        command = str((payload.get("tool_input") or {}).get("command") or "")
        findings = analyze(command, str(payload.get("cwd") or os.getcwd()))
    except Exception as error:
        sys.stderr.write("guard: internal error, failing open: %s\n" % error)
        return
    if not findings:
        return
    unique = []
    for item in findings:
        if item not in unique:
            unique.append(item)
    reason = "Refused. Nothing ran.\n\n" + "\n".join("  - " + item for item in unique) + "\n\nHand the user the exact command if it was intended."
    sys.stdout.write(json.dumps({"hookSpecificOutput": {"hookEventName": "PreToolUse", "permissionDecision": "deny", "permissionDecisionReason": reason}}))


if __name__ == "__main__":
    main()
